set(ZLIB_SOURCES 	zlib/adler32.c
					zlib/compress.c
					zlib/crc32.c
					zlib/deflate.c
					zlib/gzio.c
					zlib/infblock.c
					zlib/infcodes.c
					zlib/inffast.c
					zlib/inflate.c
					zlib/inftrees.c
					zlib/infutil.c
					zlib/trees.c
					zlib/uncompr.c)
set(LIBJPEG_SOURCES libjpeg/cdjpeg.c
					libjpeg/cjpeg.c
					libjpeg/example.c
					libjpeg/jcapimin.c
					libjpeg/jcapistd.c
					libjpeg/jccoefct.c
					libjpeg/jccolor.c
					libjpeg/jcdctmgr.c
					libjpeg/jchuff.c
					libjpeg/jcinit.c
					libjpeg/jcmainct.c
					libjpeg/jcmarker.c
					libjpeg/jcmaster.c
					libjpeg/jcomapi.c
					libjpeg/jcparam.c
					libjpeg/jcphuff.c
					libjpeg/jcprepct.c
					libjpeg/jcsample.c
					libjpeg/jctrans.c
					libjpeg/jdapimin.c
					libjpeg/jdapistd.c
					libjpeg/jdatadst.c
					libjpeg/jdatasrc.c
					libjpeg/jdcoefct.c
					libjpeg/jdcolor.c
					libjpeg/jddctmgr.c
					libjpeg/jdhuff.c
					libjpeg/jdinput.c
					libjpeg/jdmainct.c
					libjpeg/jdmarker.c
					libjpeg/jdmaster.c
					libjpeg/jdmerge.c
					libjpeg/jdphuff.c
					libjpeg/jdpostct.c
					libjpeg/jdsample.c
					libjpeg/jdtrans.c
					libjpeg/jerror.c
					libjpeg/jfdctflt.c
					libjpeg/jfdctfst.c
					libjpeg/jfdctint.c
					libjpeg/jidctflt.c
					libjpeg/jidctfst.c
					libjpeg/jidctint.c
					libjpeg/jidctred.c
					libjpeg/jmemansi.c
					libjpeg/jmemmgr.c
					libjpeg/jquant1.c
					libjpeg/jquant2.c
					libjpeg/jutils.c
					libjpeg/rdbmp.c
					libjpeg/rdcolmap.c
					libjpeg/rdgif.c
					libjpeg/rdppm.c
					libjpeg/rdswitch.c
					libjpeg/rdtarga.c
					libjpeg/transupp.c
					libjpeg/wrbmp.c
					libjpeg/wrgif.c
					libjpeg/wrppm.c
					libjpeg/wrtarga.c)
set(LIBPNG_SOURCES 	libpng/png.c
					libpng/pngerror.c
					libpng/pnggccrd.c
					libpng/pngget.c
					libpng/pngmem.c
					libpng/pngpread.c
					libpng/pngread.c
					libpng/pngrio.c
					libpng/pngrtran.c
					libpng/pngrutil.c
					libpng/pngset.c
					libpng/pngtest.c
					libpng/pngtrans.c
					libpng/pngvcrd.c
					libpng/pngwio.c
					libpng/pngwrite.c
					libpng/pngwtran.c
					libpng/pngwutil.c
					)
set(TASQUAKE_SOURCES 	Source/cd_win.c
						Source/chase.c
						Source/cl_demo.c
						Source/cl_input.c
						Source/cl_main.c
						Source/cl_parse.c
						Source/cl_slist.c
						Source/cl_tent.c
						Source/cmd.c
						Source/common.c
						Source/conproc.c
						Source/console.c
						Source/crc.c
						Source/cvar.c
						Source/gl_decals.c
						Source/gl_draw.c
						Source/gl_mesh.c
						Source/gl_model.c
						Source/gl_refrag.c
						Source/gl_rlight.c
						Source/gl_rmain.c
						Source/gl_rmisc.c
						Source/gl_rpart.c
						Source/gl_rsurf.c
						Source/gl_screen.c
						Source/gl_warp.c
						Source/host.c
						Source/host_cmd.c
						Source/image.c
						Source/in_win.c
						Source/iplog.c
						Source/keys.c
						Source/mathlib.c
						Source/menu.c
						Source/movie.c
						Source/movie_avi.c
						Source/nehahra.c
						Source/net_dgrm.c
						Source/net_loop.c
						Source/net_main.c
						Source/net_vcr.c
						Source/net_win.c
						Source/net_wins.c
						Source/net_wipx.c
						Source/pr_cmds.c
						Source/pr_edict.c
						Source/pr_exec.c
						Source/r_part.c
						Source/sbar.c
						Source/security.c
						Source/snd_dma.c
						Source/snd_mem.c
						Source/snd_mix.c
						Source/snd_win.c
						Source/sv_main.c
						Source/sv_move.c
						Source/sv_phys.c
						Source/sv_user.c
						Source/sys_win.c
						Source/tas/afterframes.cpp
						Source/tas/draw.cpp
						Source/tas/hooks.cpp
						Source/tas/hud.cpp
						Source/tas/reset.cpp
						Source/tas/script_parse.cpp
						Source/tas/script_playback.cpp
						Source/tas/simulate.cpp
						Source/tas/strafing.cpp
						Source/tas/test.cpp
						Source/tas/utils.cpp
						Source/version.c
						Source/vid_common_gl.c
						Source/vid_wgl.c
						Source/view.c
						Source/wad.c
						Source/world.c
						Source/zone.c)